### ISSUE TITLE
LibreSSL: Key off of MK_LIBRESSL

### ISSUE THREAD

**Issue by lattera** [HardenedBSD/hardenedBSD-playground#3]
As it stands, we are not keying off of MK_LIBRESSL to detect whether to build "ALL THE LIBRESSL THINGS!" Modify LibreSSL's `Makefile`s to utilize the FreeBSD build framework (bsd.lib.mk, bsd.prog.mk, etc.). Doing so will allow us to fully tie in to using `src.conf(5)` and the src.opts.mk framework.

**Comment by Sp1l** [comment]
This what you mean? f4a4706a196f3bb1cc18311cdee30e2aa5dd0a2a

Still need to test is, merging master and rebuilding!

**Comment by Sp1l** [comment]
Aha! Must include src.opts.mk not bsd.opts.mk! See 3f3b5281b0938d93e947737f52462b969909aad1 build is running and compiles LibreSSL not Open.

Build finished successfully.
